---
title: "Group Work Plan"
subtitle: "STT2860 F22 Project 02"
author: "Authors: ALL GROUP MEMBER NAMES HERE"
date: "`r format(Sys.time(), '%A, %B %d, %Y @ %I:%M %p')`"
output: 
  html_document: 
    theme: yeti
    highlight: textmate
---
***

**Work Plan/Assignments**

group work plan:

1(work plan/assignments). We will all be responsible for completing work on this project. Nichole Johnson will be the one to submit the group portion, work plan, and work update of this project. We will all individually upload our final portions of our individual parts. If we split up work, we plan on communicating to each other on how to do so if we decide to split up work outside of class at all.
2(completion timeline). We plan on completing this project during class on 11/8 and 11/10. If we are not able to finish our group portion during these class times, we plan to communicate over text and make our next steps and plans on how we should move forward on finishing this project together. 
3.We plan to communicate via text message if we need to discuss the project outside of class.

**Work Plan/Assignments Update**
Our workplan has not changed from what we said it would be in the original plan. Nichole submitted the original plan and we have collectively worked on the graphs. Taylor played a big role in completing graphs 1-3. We plan to finish graphs 3-5 during class time should R Studio cooperate. 

**Completion Timeline**

According to our original timeline we are still on track. We have completed most parts up to graph 4 and we will plan to finish all of the work by the end of class. Any work that is not completed that will need to be done outside of class we will split up amongst each other.

**Communication Plan**

Our communication plan is still the same and so far everyone has communicated in an effective and timely manner.

***
